INSERT INTO Pessoas VALUES
    (1, 'Miguel Silva', 'm', '2001-09-02'),
    (2, 'Celso Silva', 'm', '1972-11-09'),
    (3, 'Elsa Guerreiro', 'f', '1973-03-03'),
    (4, 'Jose Silva', 'm', '1969-08-03'),
    (5, 'Helia Boto', 'f', '1971-03-10'),
    (6, 'Virgilio Guerreiro', 'm', '1969-09-02'),
    (7, 'Rogelia De Jesus Martins Dos Santos', 'f', '1970-01-27'),
    (8, 'Sara Boto', 'f', NULL),
    (9, 'Tiago Guerreiro', 'm', NULL),
    (10, 'Inacio Jose', 'm', NULL),
    (11, 'Isabel Conceicao', 'f', NULL),
    (12, 'Jose Santana Boto (Escuna)', 'm', NULL),
    (13, 'Amelia', 'f', NULL),
    (14, 'Manuel Coelho Lourenco', 'm', NULL),
    (15, 'Maria Guerreiro', 'f', NULL),
    (16, 'Joaquim lapa dos santos', 'm', NULL),
    (17, 'Maria de Jesus', 'f', NULL),
    (18, 'Leonor Castro', 'f', NULL),
    (19, 'Guilherme Guerreiro', 'm', '2014-09-02'),
    (20, 'Rafael Guerreiro', 'm', NULL),
    (21, 'Domingos coelho', 'm', NULL),
    (22, 'Jose Manuel Coelho', 'm', NULL),
    (23, 'Almerinda Guerreiro Coelho', 'f', NULL),
    (24, 'Jose Joaquim lapa dos santos', 'm', NULL),
    (25, 'Cremilde maria lapa dos santos', 'f', NULL),
    (26, 'Maria Aliete Lapa Dos Santos', 'f', NULL),
    (27, 'Miguel Castro', 'm', NULL),
    (28, 'Susana Pereira', 'f', NULL),
    (29, 'Manuel Antonio', 'm', NULL),
    (30, 'Maria Lusia', 'f', NULL),
    (31, 'Manuel Lourenco', 'm', NULL),
    (32, 'Maria vitoria Florinda', 'f', NULL),
    (33, 'Joaquim dos Santos', 'm', NULL),
    (34, 'Maria Dos Reis', 'f', NULL),
    (35, 'Antonio Francisco', 'm', NULL),
    (36, 'Teresa de Jesus', 'f', NULL),
    (37, 'Daniel Coelho', 'm', NULL),
    (38, 'Pedro Coelho', 'm', NULL),
    (39, 'Mariana coelho', 'f', NULL),
    (40, 'Eugenia', 'f', NULL),
    (41, 'Antonio Coelho Lourenco', 'm', NULL),
    (42, 'Ventura', 'm', NULL),
    (43, 'Joaquim Antonio', 'm', NULL),
    (44, 'Piedade', 'f', NULL),
    (45, 'Maria Beatriz', 'f', NULL),
    (46, 'Humberto Guerreiro', 'm', NULL),
    (47, 'Maria Jose', 'f', NULL),
    (48, 'Saltina', 'f', NULL),
    (49, 'Abel Pereira', 'm', NULL),
    (50, 'Filomena', 'f', NULL),
    (51, 'Fatima Coelho', 'f', NULL),
    (52, 'Irma', 'f', NULL),
    (53, 'Joaquim Lucrecia guerreiro', 'm', NULL),
    (54, 'Anibal Correia Martins', 'm', NULL),
    (55, 'Desconhecido Antonio', 'm', NULL),
    (56, 'Desconhecido Lusia', 'f', NULL),
    (57, 'Carolina', 'f', NULL),
    (58, 'Dinis', 'm', NULL),
    (59, 'Julia Antonio', 'f', NULL),
    (60, 'Alexandrina Antonio', 'f', NULL),
    (61, 'Prepetua Antonio', 'f', NULL),
    (62, 'Manuel Lusia', 'm', NULL),
    (63, 'Antonio', 'm', NULL),
    (64, 'Jose', 'm', NULL),
    (65, 'Francisco', 'm', NULL),
    (66, 'Daniel', 'm', NULL),
    (67, 'Joana Guerreiro', 'f', NULL),
    (68, 'Daniela guerreiro', 'f', NULL),
    (69, 'Vera', 'f', NULL),
    (70, 'Philippe Gomes', 'm', NULL),
    (71, 'David', 'm', NULL),
    (72, 'Luis Martins', 'm', NULL),
    (73, 'Armirinda', 'f', NULL),
    (74, 'Dulce morgado', 'f', NULL),
    (75, 'Dario Martins', 'm', NULL),
    (76, 'Rui Martins', 'm', NULL),
    (77, 'Paulo Martins', 'm', NULL),
    (78, 'Clarisse Martins', 'f', NULL),
    (79, 'Joao Guerreiro', 'm', NULL),
    (80, 'Julia Da Assuncao', 'f', NULL),
    (81, 'Maria Balbina', 'f', NULL),
    --fake
    (82,'Falso Mae1','f',NULL),
    (83, 'Falso Pai1','f',NULL),
    (84,'Falso Mae2','f',NULL),
    (85, 'Falso Pai2','f',NULL),
    (86,'Filho de mae1 e pai2','m',NULL),
    (87,'Filho de mae1 e de pai1','m',NULL),
    (88,'Filho de mae1 e pai1','m',NULL),
    (89,'Filho de mae2 e pai1','m',NULL);

   
INSERT INTO MaeDe VALUES
(3,1),
(28,19),
(28,20),
(8,18),
(5,8),
(5,2),
(7,9),
(7,3),
(17,7),
(17,24),
(17,25),
(17,26),
(30,14),
(32,15), --
(34,16),
(36,17),
(56,30),
(11,4),
(13,5),
(15,6), --
 --fake
(82,86),
(82,87),
(82,88),
(84,89);



INSERT INTO PaiDe VALUES
(2,1),
(27,18),
(9,19),
(9,20),
(4,8),
(4,2),
(6,3),
(6,9),
(10,4),
(12,5),
(14,6), --
(16,7),
(16,24),
(16,25),
(16,26),
(35,17),
(33,16),
(31,15), --
(29,14),
(55,29),
--fake
(85,86),
(83,87),
(83,88),
(83,89);